# Generated by Django 5.1.7 on 2025-04-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpeedTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_speed', models.FloatField()),
                ('upload_speed', models.FloatField()),
                ('tested_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WiFiNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid', models.CharField(max_length=100)),
                ('signal_strength', models.IntegerField()),
                ('channel', models.CharField(max_length=10)),
                ('security', models.CharField(max_length=50)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
